In [1]:
import pytest

# Introduction to Python: Exercises


**What is 5 to the power of 7?**

In [2]:
%%file pow_exercise.py

def pow_5_7():
  # Include your code in the next line
  return 5**7


Writing pow_exercise.py


**Split this string:**

    s = "Hi there Migue!"
    
**into a list.**

In [3]:
%%file split_string_exercise.py

def split_string():
  s = "Hi there Migue!"
  # Include your code in the next line
  return s.split()
  

Writing split_string_exercise.py


**Given the variables:**

    planet = "Earth"
    diameter = 12742

**Use .format() to print the following string:**

    The diameter of Earth is 12742 kilometers.

In [23]:
%%file format_Earth_diameter_exercise.py

def format_Earth_diameter():
  planet = "Earth"
  diameter = 12742
  # Include your code in the next line
  return ('The diameter of {0} is {1} kilometers.'.format(planet,diameter))


Overwriting format_Earth_diameter_exercise.py


**Given this nested list, use indexing to grab the word "hello"**

In [5]:
%%file get_value_nested_list_exercise.py

def get_value_nested_list():
  lst = [1,4.7,[9,4],[5,[100,200,['hello']],23,11],1,7]
  # Include your code in the next line
  return lst[3][1][2][0]


Writing get_value_nested_list_exercise.py


**Given this nested dictionary, get the word "Network".**

In [6]:
%%file get_value_nested_dict_exercise.py

def get_value_nested_dict():
  dict = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'Network']}]}]}
  # Include your code in the next line
  return dict['k1'][3]['tricky'][3]['target'][3]

Writing get_value_nested_dict_exercise.py


**Create a function named get_domain, that receives a parameter with an email address, and returns the  domain from a string in the form:**

    user@domain.com
    
**So for example, passing "user@domain.com" the function returns: domain.com**

In [7]:
%%file get_domain_exercise.py

# Include your code in the next line
def get_domain(email):
  return email.split('@')[1]


Writing get_domain_exercise.py


**Create a function contains_word that recives the parameters str and sentence, returns True if sentence contains a word with the value of str; otherwise, the function returns False. Examples:**



```
contains_word('compute', 'This is my computer') == False
contains_word('This', 'This is my computer') == True
```



In [8]:
%%file contains_word_exercise.py

# Include your code in the next line
def contains_word(word, sentence):
    lst = sentence.split()
    return word in lst


Writing contains_word_exercise.py


** Create a function count_word_occurrence that receives the parameters w and sentence, and counts the number of times the word containing the value of w occurs in a string. Example:**


```
count_word_occurrence('compute', 'This computer computes faster')==0
count_word_occurrence('computer', 'This computer is faster than that computer')==2
```



In [9]:
%%file count_word_occurrence_exercise.py

# Include your code in the next line
def count_word_occurrence(word, sentence):
    lst = sentence.split()
    count = 0
    for elem in lst:
        if elem == word:
            count += 1
    return count


Writing count_word_occurrence_exercise.py


**Creat a function remove_words that receives a parameter lst and uses lambda expressions and the filter() function to select words from a list that don't start with the letter 's'. For example:**



```
remove_words(['soup','dog','salad','cat','great'])
```

returns:

`    ['dog', 'cat', 'great']`

In [21]:
%%file remove_words_exercise.py

# Include your code in the next line
def remove_words(lst):
    return list(filter(lambda x: x[0] != 's', lst))



Overwriting remove_words_exercise.py


# Numpy Arrays: Exercises 

In [11]:
import numpy as np

**Create a function np_zeros that receives a parameter length a return a numpy array of length zeros**
```
np_zeros(10)
```
returns
```
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

In [12]:
%%file np_zeros_exercise.py
import numpy as np

# Include your code in the next line
def np_zeros(l):
    return np.zeros(l)

Writing np_zeros_exercise.py


**Create a function np_ones that receives a parameter length a return a numpy array of length ones. Example**

```
np_ones(10)
```
returns
```
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
```

In [13]:
%%file np_ones_exercise.py
import numpy as np

# Include your code in the next line
def np_ones(l):
    return np.ones(l)

np_ones(10)

Writing np_ones_exercise.py


**Create a function np_ns that receives a parameter length and a parameter n, and returns a numpy array of length n. Example:**
```
np_ns(10, 3)
```
returns
```
array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])
```

In [14]:
%%file np_ns_exercise.py
import numpy as np

# Include your code in the next line
def np_ns(l,n):
    return np.full([l],n, dtype = float)


Writing np_ns_exercise.py


**Create a function np_ints that receives parameters low and high and returns a numpy array of the integers from low to high. Example:**
```
np_inst(1, 5)
```
returns
```
array([ 1,  2,  3,  4,  5])
```

In [15]:
%%file np_ints_exercises.py
import numpy as np

# Include your code in the next line
def np_ints(l,h):
    return np.arange(l,h+1,1)

Writing np_ints_exercises.py


**Create a function np_even_ints that receives parameters low and high and returns a numpy array of the even integers from low to high. Example:**
```
np_even_inst(1, 5)
```
returns
```
array([ 2,  4])
```

In [16]:
%%file np_even_ints_exercises.py
import numpy as np

# Include your code in the next line
def np_even_ints(l,h):
    res = np.arange(l,h+1,1)
    return res[res%2 == 0]

Writing np_even_ints_exercises.py


**Create a function np_matrix_ints that receives parameters row_count,  col_count, and start and returns a numpy matrix as follows:**
```
np_matrix_ints(2, 3, 4)
```
returns
```
array([[4, 5, 6],
       [7, 8, 9]])
```


In [17]:
%%file np_matrix_ints_exercises.py
import numpy as np

# Include your code in the next line
def np_matrix_ints(row_count,col_count,start):
    res = np.arange(start,start + row_count*col_count,1)
    return res.reshape(row_count,col_count)

Writing np_matrix_ints_exercises.py


**Create a function np_right_bottom_matrix that receives parameters matrix, right, and top and returns the bottom-right numpy matrix as follows:**
```
matrix = np.array([[ 1,  2,  3,  4,  5], [ 6,  7,  8,  9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
np_right_bottom_matrix(matrix, 2, 1)
```
returns
```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```


In [18]:
%%file np_right_bottom_matrix_exercises.py
import numpy as np

# Include your code in the next line
def np_right_bottom_matrix(matrix,right,top):
    return matrix[right:,top:]

Writing np_right_bottom_matrix_exercises.py


# Tests

In [19]:
%%file test_exercises.py
import numpy as np

from np_right_bottom_matrix_exercises import *
def test_np_right_bottom_matrix():
  matrix = np.arange(1,26).reshape(5,5)
  assert (np_right_bottom_matrix(matrix, 2, 1) == np.array([[12, 13, 14, 15],[17, 18, 19, 20],[22, 23, 24, 25]])).all()

  assert (np_right_bottom_matrix(matrix, 0, 3) == np.array([[ 4,  5],[ 9, 10],[14, 15],[19, 20],[24, 25]])).all()

from np_matrix_ints_exercises import *
def test_np_matrix_ints():
  m = np_matrix_ints(3, 3, 0)
  assert (m == np.arange(0,9).reshape(3,3)).all() and m.shape == (3,3)

  m = np_matrix_ints(3, 5, 20)
  assert (m == np.arange(20,35).reshape(3,5)).all() and m.shape == (3,5)

  m = np_matrix_ints(1, 5, 5)
  assert (m == np.arange(5,10).reshape(1,5)).all() and m.shape == (1,5)

  m = np_matrix_ints(7, 1, 91)
  assert (m == np.arange(91,98).reshape(7,1)).all() and m.shape == (7,1) 


from np_even_ints_exercises import *
def test_np_even_ints():
  arr = np_even_ints(4, 7)
  assert (arr==np.array([ 4, 6])).all() and arr.shape[0]==2

  arr = np_even_ints(99, 111)
  assert (arr==np.array([ 100,  102,  104,  106, 108, 110])).all() and arr.shape[0]==6


from np_ints_exercises import *
def test_np_ints():
  arr = np_ints(4, 7)
  assert (arr==np.array([ 4, 5, 6, 7])).all() and arr.shape[0]==4

  arr = np_ints(100, 111)
  assert (arr==np.array([ 100,  101,  102,  103,  104,  105,  106,  107,  108,  109, 110, 111])).all() and arr.shape[0]==12


from np_ns_exercise import *
def test_np_ns():
  arr = np_ns(1, 4)
  assert (arr==np.array([ 4.])).all() and arr.shape[0]==1

  arr = np_ns(12, 1)
  assert (arr==np.array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 1., 1.])).all() and arr.shape[0]==12


from np_ones_exercise import *
def test_np_ones():
  arr = np_ones(1)
  assert (arr==np.array([ 1.])).all() and arr.shape[0]==1

  arr = np_ones(10)
  assert (arr==np.array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])).all() and arr.shape[0]==10


from np_zeros_exercise import *
def test_np_zeros():
  arr = np_zeros(1)
  assert (arr==np.array([ 0.])).all() and arr.shape[0]==1

  arr = np_zeros(10)
  assert (arr==np.array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])).all() and arr.shape[0]==10


from remove_words_exercise import *
def test_remove_words():
  assert remove_words(['soup','dog','salad','cat','great'])==['dog', 'cat', 'great']
  assert remove_words(['soyd','salad','book','salt'])==['book']


from count_word_occurrence_exercise import *
def test_count_word_occurrence():
  assert count_word_occurrence('compute', 'This computer computes faster')==0
  assert count_word_occurrence('computer', 'This computer is faster than that computer')==2


from contains_word_exercise import *
def test_contains_word():
  assert contains_word('compute', 'This is my computer') == False
  assert contains_word('This', 'This is my computer') == True


from get_domain_exercise import *
def test_get_domain():
  assert get_domain('migue@tec.mx') == 'tec.mx'
  assert get_domain('miguel.medina@somedomain.com.mx') == 'somedomain.com.mx'


from get_value_nested_dict_exercise import *
def test_get_value_nested_dict():
  assert get_value_nested_dict() == 'Network'


from get_value_nested_list_exercise import *
def test_get_value_nested_list():
  assert get_value_nested_list() == 'hello'


from format_Earth_diameter_exercise import *
def test_format_Earth_diameter():
  assert format_Earth_diameter() == 'The diameter of Earth is 12742 kilometers.'


from split_string_exercise import *
def test_split_string():
  assert split_string() == ['Hi', 'there', 'Migue!']


from pow_exercise import *
def test_pow_5_7():
  assert pow_5_7() == 78125


Writing test_exercises.py


In [24]:
!python -m pytest test_exercises.py 

============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.10.0, pluggy-0.7.1
rootdir: /content, inifile:
plugins: typeguard-2.7.1
collected 16 items                                                             

test_exercises.py ................                                       [100%]

========================== 16 passed in 0.16 seconds ===========================
